version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4173:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx
    image: nginx:1.25-alpine3.17
    ports:
     - "5173:80"
    volumes:
      - "./client/nginx.conf:/etc/nginx/conf.d/default.conf"


